

export const brandImages = [
    {image:'deFabulous.webp'},
    {image:'forever52.webp'},
    {image:'gk.webp'},
    {image:'glowhiteherbals.webp'},
    {image:'ikonic.webp'},
    {image:'kryolan.webp'},
    {image:'lakme.webp'},
    {image:'loreal.webp'},
    {image:'mac.webp'},
    {image:'makeup-studio.webp'},
    {image:'matrix.webp'},
    {image:'maybelline.webp'},
    {image:'mr-barber.webp'},
    {image:'nars.webp'},
    {image:'o3+.webp'},
    {image:'ozone.webp'},
    {image:'pac.webp'},
    {image:'recode.webp'},
    {image:'revolution.webp'},
    {image:'rica.webp'},
    {image:'schwarzkop.webp'},
    {image:'streax.webp'},
    {image:'sugar.webp'},
    {image:'velvettree.webp'},
    {image:'vlcc.webp'},
    {image:'wahl.webp'},
    {image:'wella.webp'},
]

